### ISSUE TITLE
Looking for sources for corpora

### ISSUE THREAD

**Issue by caufieldjh** [caufieldjh/awesome-bioie#1]
Would like to add more corpora but don't have stable links for them yet.
The first one is MiPACQ:
[paper](https://academic.oup.com/jamia/article/20/5/922/2909262) - the Multi-source Integrated Platform for Answering Clinical Questions corpus, containing 13,091 sentences from clinical narratives, all annotated for syntactic structure and named entities.

Looks like it should be at http://clear.colorado.edu/compsem/index.php?page=endendsystems&sub=mipacq but that link doesn't appear live at the moment.

**Comment by caufieldjh** [comment]
SHARPn NLP Seed Corpus - [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0112774) - clinical notes from pulmonary arterial disease and breast cancer patients.

That paper may not be quite right.

**Comment by caufieldjh** [comment]
SHARPn Stratified Corpus - this and the previous set seem like they should be at http://informatics.mayo.edu/sharp/index.php/Tools but I haven't found download links for the corpora.

**Comment by caufieldjh** [comment]
> Would like to add more corpora but don't have stable links for them yet.
> The first one is MiPACQ:
> [paper](https://academic.oup.com/jamia/article/20/5/922/2909262) - the Multi-source Integrated Platform for Answering Clinical Questions corpus, containing 13,091 sentences from clinical narratives, all annotated for syntactic structure and named entities.
> 
> Looks like it should be at http://clear.colorado.edu/compsem/index.php?page=endendsystems&sub=mipacq but that link doesn't appear live at the moment.

The Colorado CLEAR page is accessible but doesn't have an obvious link to the MiPACQ corpus.
Looks like usage may still require coordination through Mayo Clinic?

**Comment by caufieldjh** [comment]
Gave up looking for these - inaccessible data sets are Not Awesome.

**Comment by drussellmrichie** [comment]
Hi, @caufieldjh. It's a shame that it's not easier to access these. Did you ever get access? I'm also trying to get access to MiPACQ and SHARP (and THYME, too).

**Comment by caufieldjh** [comment]
Hi @drussellmrichie - not sure about the others, but THYME colon cancer splits are here: https://github.com/stylerw/thymedata

**Comment by drussellmrichie** [comment]
Not sure if you're still interested in this, but for you or anyone else who comes across this, according to an email that my PI just received from Guergana Savova, who co-leads hNLP:

"the MiPACQ and SHARP corpora are not available for distribution at this point."

😦😦😦😦😦😦😦😦

I'll post here if I here anything else....

**Comment by caufieldjh** [comment]
Oh well! Thanks for forwarding the official word, even if it's disappointing.
